# Cloudflare Pages configuration
# This file provides instructions to Cloudflare Pages on how to build and deploy your Next.js application

[build]
  command = "npm run build"
  publish = ".next" # Next.jsのビルド出力先
  environment = { NODE_VERSION = "18" }

[build.environment]
  # 必要な環境変数があればここに追加（機密情報は含めないこと）
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Path = {match_not = ["/_next/*", "/static/*", "/api/*", "/favicon.ico", "/robots.txt", "/sitemap.xml"]}}
